// Movie database with details for each movie
export const movies = [
  {
    title: "Avatar",
    director: "James Cameron",
    year: 2009,
    genre: "Action",
    gross: 2923710708,
    oscars: 3,
    rating: "PG-13",
  },
  {
    title: "Avengers: End Game",
    director: "Anthony Russo",
    year: 2019,
    genre: "Action",
    gross: 2799439100,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Avatar: The Way of Water",
    director: "James Cameron",
    year: 2022,
    genre: "Action",
    gross: 2320250281,
    oscars: 1,
    rating: "PG-13",
  },
  {
    title: "Titanic",
    director: "James Cameron",
    year: 1997,
    genre: "Romance",
    gross: 2264812968,
    oscars: 11,
    rating: "PG-13",
  },
  {
    title: "Star Wars: Episode VII - The Force Awakens",
    director: "J.J. Abrams",
    year: 2015,
    genre: "Action",
    gross: 2071310218,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Avengers: Infinity War",
    director: "Anthony Russo",
    year: 2018,
    genre: "Action",
    gross: 2052415039,
    oscars: 1,
    rating: "PG-13",
  },
  {
    title: "Spider-Man: No Way Home",
    director: "Jon Watts",
    year: 2021,
    genre: "Action",
    gross: 1921426073,
    oscars: 1,
    rating: "PG-13",
  },
  {
    title: "Ne Zha 2",
    director: "Yu Yang",
    year: 2025,
    genre: "Animation",
    gross: 1899796467,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Inside Out 2",
    director: "Kelsey Mann",
    year: 2024,
    genre: "Animation",
    gross: 1698863816,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Jurassic World",
    director: "Colin Trevorrow",
    year: 2015,
    genre: "Action",
    gross: 1671537444,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Lion King",
    director: "Jon Favreau",
    year: 2019,
    genre: "Animation",
    gross: 1662020819,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "The Avengers",
    director: "Joss Whedon",
    year: 2012,
    genre: "Action",
    gross: 1520538536,
    oscars: 1,
    rating: "PG-13",
  },
  {
    title: "Furious 7",
    director: "James Wan",
    year: 2015,
    genre: "Action",
    gross: 1515342457,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Top Gun: Maverick",
    director: "Joseph Kosinski",
    year: 2022,
    genre: "Action",
    gross: 1495696292,
    oscars: 1,
    rating: "PG-13",
  },
  {
    title: "Frozen II",
    director: "Chris Buck",
    year: 2019,
    genre: "Animation",
    gross: 1453683476,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Barbie",
    director: "Greta Gerwig",
    year: 2023,
    genre: "Drama",
    gross: 1447038421,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Avengers: Age of Ultron",
    director: "Joss Whedon",
    year: 2015,
    genre: "Action",
    gross: 1405018048,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Super Mario Bros. Movie",
    director: "Aaron Horvath",
    year: 2023,
    genre: "Drama",
    gross: 1360847665,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Black Panther",
    director: "Ryan Coogler",
    year: 2018,
    genre: "Action",
    gross: 1349926083,
    oscars: 3,
    rating: "PG-13",
  },
  {
    title: "Harry Potter and the Deathly Hallows: Part 2",
    director: "David Yates",
    year: 2011,
    genre: "Fantasy",
    gross: 1342505340,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Deadpool & Wolverine",
    director: "Shawn Levy",
    year: 2024,
    genre: "Drama",
    gross: 1338073645,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Star Wars: Episode VIII - The Last Jedi",
    director: "Rian Johnson",
    year: 2017,
    genre: "Action",
    gross: 1334407706,
    oscars: 4,
    rating: "PG-13",
  },
  {
    title: "Jurassic World: Fallen Kingdom",
    director: "J.A. Bayona",
    year: 2018,
    genre: "Action",
    gross: 1310469037,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Frozen",
    director: "Chris Buck",
    year: 2013,
    genre: "Animation",
    gross: 1286319131,
    oscars: 2,
    rating: "PG",
  },
  {
    title: "Beauty and the Beast",
    director: "Bill Condon",
    year: 2017,
    genre: "Musical",
    gross: 1266115964,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Incredibles 2",
    director: "Brad Bird",
    year: 2018,
    genre: "Animation",
    gross: 1243225667,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "The Fate of the Furious",
    director: "F. Gary Gray",
    year: 2017,
    genre: "Action",
    gross: 1236009236,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Iron Man 3",
    director: "Shane Black",
    year: 2013,
    genre: "Action",
    gross: 1215577205,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Minions",
    director: "Kyle Balda",
    year: 2015,
    genre: "Animation",
    gross: 1159457503,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Captain America: Civil War",
    director: "Anthony Russo",
    year: 2016,
    genre: "Action",
    gross: 1155046416,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Aquaman",
    director: "James Wan",
    year: 2018,
    genre: "Drama",
    gross: 1152028393,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Lord of the Rings: The Return of the King",
    director: "Peter Jackson",
    year: 2003,
    genre: "Drama",
    gross: 1138585547,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Spider-Man: Far from Home",
    director: "Jon Watts",
    year: 2019,
    genre: "Drama",
    gross: 1132723226,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Captain Marvel",
    director: "Anna Boden",
    year: 2019,
    genre: "Drama",
    gross: 1131416446,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Transformers: Dark of the Moon",
    director: "Michael Bay",
    year: 2011,
    genre: "Action",
    gross: 1123794079,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Dark Knight Rises",
    director: "Christopher Nolan",
    year: 2012,
    genre: "Action",
    gross: 1114976407,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Skyfall",
    director: "Sam Mendes",
    year: 2012,
    genre: "Action",
    gross: 1108594137,
    oscars: 2,
    rating: "PG-13",
  },
  {
    title: "Transformers: Age of Extinction",
    director: "Michael Bay",
    year: 2014,
    genre: "Action",
    gross: 1105261713,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Jurassic Park",
    director: "Steven Spielberg",
    year: 1993,
    genre: "Adventure",
    gross: 1104379926,
    oscars: 3,
    rating: "PG-13",
  },
  {
    title: "Joker",
    director: "Todd Phillips",
    year: 2019,
    genre: "Drama",
    gross: 1078958629,
    oscars: 2,
    rating: "R",
  },
  {
    title: "Star Wars: Episode IX - The Rise of Skywalker",
    director: "J.J. Abrams",
    year: 2019,
    genre: "Action",
    gross: 1077022372,
    oscars: 3,
    rating: "PG-13",
  },
  {
    title: "Toy Story 4",
    director: "Josh Cooley",
    year: 2019,
    genre: "Animation",
    gross: 1073841394,
    oscars: 1,
    rating: "G",
  },
  {
    title: "Toy Story 3",
    director: "Lee Unkrich",
    year: 2010,
    genre: "Animation",
    gross: 1067316101,
    oscars: 2,
    rating: "G",
  },
  {
    title: "Pirates of the Caribbean: Dead Man's Chest",
    director: "Gore Verbinski",
    year: 2006,
    genre: "Drama",
    gross: 1066179747,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Moana 2",
    director: "Dana Ledoux Miller",
    year: 2024,
    genre: "Drama",
    gross: 1059242164,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Rogue One: A Star Wars Story",
    director: "Gareth Edwards",
    year: 2016,
    genre: "Action",
    gross: 1058684742,
    oscars: 2,
    rating: "PG-13",
  },
  {
    title: "Aladdin",
    director: "Guy Ritchie",
    year: 2019,
    genre: "Musical",
    gross: 1054304000,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Pirates of the Caribbean: On Stranger Tides",
    director: "Rob Marshall",
    year: 2011,
    genre: "Adventure",
    gross: 1046721266,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Star Wars: Episode I - The Phantom Menace",
    director: "George Lucas",
    year: 1999,
    genre: "Drama",
    gross: 1046515409,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Despicable Me 3",
    director: "Pierre Coffin",
    year: 2017,
    genre: "Animation",
    gross: 1034800131,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Finding Dory",
    director: "Andrew Stanton",
    year: 2016,
    genre: "Animation",
    gross: 1029266989,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Harry Potter and the Sorcerer",
    director: "Chris Columbus",
    year: 2001,
    genre: "Fantasy",
    gross: 1028492855,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Zootopia",
    director: "Byron Howard",
    year: 2016,
    genre: "Animation",
    gross: 1025521689,
    oscars: 1,
    rating: "PG",
  },
  {
    title: "Alice in Wonderland",
    director: "Tim Burton",
    year: 2010,
    genre: "Fantasy",
    gross: 1025468216,
    oscars: 2,
    rating: "PG",
  },
  {
    title: "The Hobbit: An Unexpected Journey",
    director: "Peter Jackson",
    year: 2012,
    genre: "Fantasy",
    gross: 1017107150,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Dark Knight",
    director: "Christopher Nolan",
    year: 2008,
    genre: "Action",
    gross: 1009057329,
    oscars: 2,
    rating: "PG-13",
  },
  {
    title: "Jurassic World: Dominion",
    director: "Colin Trevorrow",
    year: 2022,
    genre: "Action",
    gross: 1001978080,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Lilo & Stitch",
    director: "Dean DeBlois",
    year: 2025,
    genre: "Animation",
    gross: 1001486676,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "The Lion King",
    director: "Jon Favreau",
    year: 1994,
    genre: "Animation",
    gross: 979161373,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Oppenheimer",
    director: "Christopher Nolan",
    year: 2023,
    genre: "Drama",
    gross: 975811333,
    oscars: 7,
    rating: "R",
  },
  {
    title: "Despicable Me 2",
    director: "Pierre Coffin",
    year: 2013,
    genre: "Animation",
    gross: 970766005,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Despicable Me 4",
    director: "Chris Renaud",
    year: 2024,
    genre: "Animation",
    gross: 969607599,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "The Jungle Book",
    director: "Jon Favreau",
    year: 2016,
    genre: "Family",
    gross: 967724775,
    oscars: 1,
    rating: "PG",
  },
  {
    title: "Jumanji: Welcome to the Jungle",
    director: "Jake Kasdan",
    year: 2017,
    genre: "Adventure",
    gross: 962544585,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Hobbit: The Battle of the Five Armies",
    director: "Peter Jackson",
    year: 2014,
    genre: "Fantasy",
    gross: 962253946,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Pirates of the Caribbean: At World",
    director: "Gore Verbinski",
    year: 2007,
    genre: "Adventure",
    gross: 961691209,
    oscars: 1,
    rating: "PG-13",
  },
  {
    title: "Harry Potter and the Deathly Hallows: Part 1",
    director: "David Yates",
    year: 2010,
    genre: "Fantasy",
    gross: 960858478,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Hobbit: The Desolation of Smaug",
    director: "Peter Jackson",
    year: 2013,
    genre: "Adventure",
    gross: 959079095,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Doctor Strange in the Multiverse of Madness",
    director: "Sam Raimi",
    year: 2022,
    genre: "Action",
    gross: 955775804,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "A Minecraft Movie",
    director: "Jared Hess",
    year: 2025,
    genre: "Animation",
    gross: 955149195,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Harry Potter and the Order of the Phoenix",
    director: "David Yates",
    year: 2007,
    genre: "Fantasy",
    gross: 942871730,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Finding Nemo",
    director: "Andrew Stanton",
    year: 2003,
    genre: "Animation",
    gross: 941637960,
    oscars: 1,
    rating: "G",
  },
  {
    title: "Harry Potter and the Half-Blood Prince",
    director: "David Yates",
    year: 2009,
    genre: "Fantasy",
    gross: 941056063,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Minions: The Rise of Gru",
    director: "Kyle Balda",
    year: 2022,
    genre: "Animation",
    gross: 940482695,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "The Lord of the Rings: The Two Towers",
    director: "Peter Jackson",
    year: 2002,
    genre: "Adventure",
    gross: 938532865,
    oscars: 2,
    rating: "PG-13",
  },
  {
    title: "Shrek 2",
    director: "Andrew Adamson",
    year: 2004,
    genre: "Animation",
    gross: 932530034,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Bohemian Rhapsody",
    director: "Bryan Singer",
    year: 2018,
    genre: "Drama",
    gross: 910813521,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Star Wars: Episode III - Revenge of the Sith",
    director: "George Lucas",
    year: 2005,
    genre: "Action",
    gross: 905595947,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Battle at Lake Changjin",
    director: "Chen Kaige",
    year: 2021,
    genre: "War",
    gross: 902548476,
    oscars: 0,
    rating: "R",
  },
  {
    title: "Harry Potter and the Goblet of Fire",
    director: "Mike Newell",
    year: 2005,
    genre: "Fantasy",
    gross: 897468207,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Spider-Man 3",
    director: "Sam Raimi",
    year: 2007,
    genre: "Action",
    gross: 891697618,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    director: "Peter Jackson",
    year: 2001,
    genre: "Adventure",
    gross: 888483037,
    oscars: 4,
    rating: "PG-13",
  },
  {
    title: "Ice Age: Dawn of the Dinosaurs",
    director: "Carlos Saldanha",
    year: 2009,
    genre: "Animation",
    gross: 886686817,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Harry Potter and the Chamber of Secrets",
    director: "Chris Columbus",
    year: 2002,
    genre: "Fantasy",
    gross: 882926965,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Spider-Man: Homecoming",
    director: "Jon Watts",
    year: 2017,
    genre: "Action",
    gross: 880978185,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Spectre",
    director: "Sam Mendes",
    year: 2015,
    genre: "Action",
    gross: 880707597,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Ice Age: Continental Drift",
    director: "Steve Martino",
    year: 2012,
    genre: "Animation",
    gross: 877244782,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "The Secret Life of Pets",
    director: "Chris Renaud",
    year: 2016,
    genre: "Animation",
    gross: 875698161,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Batman v Superman: Dawn of Justice",
    director: "Zack Snyder",
    year: 2016,
    genre: "Action",
    gross: 874362803,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Wolf Warrior 2",
    director: "Wu Jing",
    year: 2017,
    genre: "Action",
    gross: 870325439,
    oscars: 0,
    rating: "R",
  },
  {
    title: "The Hunger Games: Catching Fire",
    director: "Francis Lawrence",
    year: 2013,
    genre: "Action",
    gross: 865011746,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Guardians of the Galaxy Vol. 2",
    director: "James Gunn",
    year: 2017,
    genre: "Action",
    gross: 863756903,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Black Panther: Wakanda Forever",
    director: "Ryan Coogler",
    year: 2022,
    genre: "Action",
    gross: 859208836,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Inside Out",
    director: "Pete Docter",
    year: 2015,
    genre: "Animation",
    gross: 859076254,
    oscars: 1,
    rating: "PG",
  },
  {
    title: "Venom",
    director: "Ruben Fleischer",
    year: 2018,
    genre: "Action",
    gross: 856085161,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Thor: Ragnarok",
    director: "Taika Waititi",
    year: 2017,
    genre: "Action",
    gross: 855301806,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Twilight Saga: Breaking Dawn - Part 2",
    director: "Bill Bannerman",
    year: 2012,
    genre: "Romance",
    gross: 848593948,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Guardians of the Galaxy Vol. 3",
    director: "James Gunn",
    year: 2023,
    genre: "Action",
    gross: 845555777,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Inception",
    director: "Unknown",
    year: 2010,
    genre: "Drama",
    gross: 839381898,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Transformers: Revenge of the Fallen",
    director: "Unknown",
    year: 2009,
    genre: "Drama",
    gross: 836304167,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Spider-Man",
    director: "Unknown",
    year: 2002,
    genre: "Drama",
    gross: 825820266,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Mission: Impossible - Fallout",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 824171374,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Wonder Woman",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 823970682,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Hi, Mom",
    director: "Unknown",
    year: 2021,
    genre: "Drama",
    gross: 822009764,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Independence Day",
    director: "Unknown",
    year: 1996,
    genre: "Drama",
    gross: 817400891,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Fantastic Beasts and Where to Find Them",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 816037575,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Coco",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 814641172,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Harry Potter and the Prisoner of Azkaban",
    director: "Unknown",
    year: 2004,
    genre: "Drama",
    gross: 808481128,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Shrek the Third",
    director: "Unknown",
    year: 2007,
    genre: "Drama",
    gross: 808308862,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Jumanji: The Next Level",
    director: "Unknown",
    year: 2019,
    genre: "Drama",
    gross: 801693929,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "E.T. the Extra-Terrestrial",
    director: "Unknown",
    year: 1982,
    genre: "Drama",
    gross: 797307407,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Pirates of the Caribbean: Dead Men Tell No Tales",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 795922298,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "2012",
    director: "Unknown",
    year: 2009,
    genre: "Drama",
    gross: 791217826,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Fast & Furious 6",
    director: "Unknown",
    year: 2013,
    genre: "Drama",
    gross: 788683342,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Indiana Jones and the Kingdom of the Crystal Skull",
    director: "Unknown",
    year: 2008,
    genre: "Drama",
    gross: 786636033,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Deadpool 2",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 785896632,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Spider-Man 2",
    director: "Unknown",
    year: 2004,
    genre: "Drama",
    gross: 784561571,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Deadpool",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 782837347,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Star Wars: Episode IV - A New Hope",
    director: "Unknown",
    year: 1977,
    genre: "Drama",
    gross: 775398507,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "No Time to Die",
    director: "Unknown",
    year: 2021,
    genre: "Drama",
    gross: 774153007,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Guardians of the Galaxy",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 773350376,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Batman",
    director: "Unknown",
    year: 2022,
    genre: "Drama",
    gross: 772319315,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Thor: Love and Thunder",
    director: "Unknown",
    year: 2022,
    genre: "Drama",
    gross: 760928081,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Fast & Furious Presents: Hobbs & Shaw",
    director: "David Leitch",
    year: 2019,
    genre: "Action",
    gross: 760732926,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Da Vinci Code",
    director: "Unknown",
    year: 2006,
    genre: "Drama",
    gross: 760200455,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Maleficent",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 759853685,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Hunger Games: Mockingjay - Part 1",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 759159711,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Amazing Spider-Man",
    director: "Unknown",
    year: 2012,
    genre: "Drama",
    gross: 758725893,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Interstellar",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 758690230,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Wicked",
    director: "Unknown",
    year: 2024,
    genre: "Drama",
    gross: 756233202,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Shrek Forever After",
    director: "Unknown",
    year: 2010,
    genre: "Drama",
    gross: 752600867,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Suicide Squad",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 749200054,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Madagascar 3: Europe",
    director: "Unknown",
    year: 2012,
    genre: "Drama",
    gross: 746921274,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "X-Men: Days of Future Past",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 746045700,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    director: "Unknown",
    year: 2005,
    genre: "Drama",
    gross: 745013115,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Monsters University",
    director: "Unknown",
    year: 2013,
    genre: "Drama",
    gross: 743559645,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Matrix Reloaded",
    director: "Unknown",
    year: 2003,
    genre: "Drama",
    gross: 741847937,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Up",
    director: "Unknown",
    year: 2009,
    genre: "Drama",
    gross: 735103954,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "F9: The Fast Saga",
    director: "Unknown",
    year: 2021,
    genre: "Drama",
    gross: 726229501,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Ne Zha",
    director: "Unknown",
    year: 2019,
    genre: "Drama",
    gross: 726225471,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Gravity",
    director: "Unknown",
    year: 2013,
    genre: "Drama",
    gross: 723753370,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Mufasa: The Lion King",
    director: "Unknown",
    year: 2024,
    genre: "Drama",
    gross: 722631756,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Amazing Spider-Man 2",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 716934779,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Dune: Part Two",
    director: "Unknown",
    year: 2024,
    genre: "Drama",
    gross: 714844358,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Captain America: The Winter Soldier",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 714421503,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Twilight Saga: Breaking Dawn - Part 1",
    director: "Unknown",
    year: 2011,
    genre: "Drama",
    gross: 712205856,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Twilight Saga: New Moon",
    director: "Unknown",
    year: 2009,
    genre: "Drama",
    gross: 711048123,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Mission: Impossible - Rogue Nation",
    director: "Unknown",
    year: 2015,
    genre: "Drama",
    gross: 710916403,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Dawn of the Planet of the Apes",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 710644566,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Transformers",
    director: "Unknown",
    year: 2007,
    genre: "Drama",
    gross: 709709780,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Mamma Mia!",
    director: "Unknown",
    year: 2008,
    genre: "Drama",
    gross: 706788538,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Fast X",
    director: "Unknown",
    year: 2023,
    genre: "Drama",
    gross: 704875015,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "It",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 704242888,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Wandering Earth",
    director: "Unknown",
    year: 2019,
    genre: "Drama",
    gross: 699992512,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Twilight Saga: Eclipse",
    director: "Unknown",
    year: 2010,
    genre: "Drama",
    gross: 698513085,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Hunger Games",
    director: "Unknown",
    year: 2012,
    genre: "Drama",
    gross: 695220619,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Mission: Impossible - Ghost Protocol",
    director: "Unknown",
    year: 2011,
    genre: "Drama",
    gross: 694713380,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Spider-Man: Across the Spider-Verse",
    director: "Unknown",
    year: 2023,
    genre: "Drama",
    gross: 690824738,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Detective Chinatown 3",
    director: "Unknown",
    year: 2021,
    genre: "Drama",
    gross: 686257563,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Forrest Gump",
    director: "Unknown",
    year: 1994,
    genre: "Drama",
    gross: 678226465,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Doctor Strange",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 677796833,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Sixth Sense",
    director: "Unknown",
    year: 1999,
    genre: "Drama",
    gross: 672806432,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Full River Red",
    director: "Unknown",
    year: 2023,
    genre: "Drama",
    gross: 670491959,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Man of Steel",
    director: "Unknown",
    year: 2013,
    genre: "Drama",
    gross: 670145518,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Ice Age 2: The Meltdown",
    director: "Unknown",
    year: 2006,
    genre: "Drama",
    gross: 667094506,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Kung Fu Panda 2",
    director: "Unknown",
    year: 2011,
    genre: "Drama",
    gross: 665692281,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Hunger Games: Mockingjay - Part 2",
    director: "Unknown",
    year: 2015,
    genre: "Drama",
    gross: 661456867,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Justice League",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 661326987,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Big Hero 6",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 657870525,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Fantastic Beasts: The Crimes of Grindelwald",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 655755901,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Pirates of the Caribbean: The Curse of the Black Pearl",
    director: "Unknown",
    year: 2003,
    genre: "Drama",
    gross: 654264546,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Men in Black³",
    director: "Unknown",
    year: 2012,
    genre: "Drama",
    gross: 654213485,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Star Wars: Episode II - Attack of the Clones",
    director: "Unknown",
    year: 2002,
    genre: "Drama",
    gross: 653780724,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Thor: The Dark World",
    director: "Unknown",
    year: 2013,
    genre: "Drama",
    gross: 644783140,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Moana",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 643332467,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Wonka",
    director: "Unknown",
    year: 2023,
    genre: "Drama",
    gross: 634502312,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Sing",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 634338409,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Kung Fu Panda",
    director: "Unknown",
    year: 2008,
    genre: "Drama",
    gross: 632384787,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Incredibles",
    director: "Unknown",
    year: 2004,
    genre: "Drama",
    gross: 631688498,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Martian",
    director: "Unknown",
    year: 2015,
    genre: "Drama",
    gross: 630621406,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Hancock",
    director: "Unknown",
    year: 2008,
    genre: "Drama",
    gross: 629443428,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Water Gate Bridge",
    director: "Unknown",
    year: 2022,
    genre: "Drama",
    gross: 626571697,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Fast Five",
    director: "Unknown",
    year: 2011,
    genre: "Drama",
    gross: 626140012,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Iron Man 2",
    director: "Unknown",
    year: 2010,
    genre: "Drama",
    gross: 623933331,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Ratatouille",
    director: "Unknown",
    year: 2007,
    genre: "Drama",
    gross: 623732061,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Ant-Man and the Wasp",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 622674139,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "How to Train Your Dragon 2",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 621537519,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Logan",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 619180476,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Lost World: Jurassic Park",
    director: "Unknown",
    year: 1997,
    genre: "Drama",
    gross: 618638999,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Casino Royale",
    director: "Unknown",
    year: 2006,
    genre: "Drama",
    gross: 616585752,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Wandering Earth II",
    director: "Unknown",
    year: 2023,
    genre: "Drama",
    gross: 615023132,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Passion of the Christ",
    director: "Unknown",
    year: 2004,
    genre: "Drama",
    gross: 610063438,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Life of Pi",
    director: "Unknown",
    year: 2012,
    genre: "Drama",
    gross: 609016565,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Ready Player One",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 607874422,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Transformers: The Last Knight",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 605425157,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Madagascar: Escape 2 Africa",
    director: "Unknown",
    year: 2008,
    genre: "Drama",
    gross: 603900354,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "War of the Worlds",
    director: "Unknown",
    year: 2005,
    genre: "Drama",
    gross: 603873504,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Tangled",
    director: "Unknown",
    year: 2010,
    genre: "Drama",
    gross: 591806017,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Quantum of Solace",
    director: "Unknown",
    year: 2008,
    genre: "Drama",
    gross: 589593688,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Men in Black",
    director: "Unknown",
    year: 1997,
    genre: "Drama",
    gross: 589390539,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Croods",
    director: "Unknown",
    year: 2013,
    genre: "Drama",
    gross: 587266745,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Hangover Part II",
    director: "Unknown",
    year: 2011,
    genre: "Drama",
    gross: 586764305,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Iron Man",
    director: "Unknown",
    year: 2008,
    genre: "Drama",
    gross: 585796247,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "I Am Legend",
    director: "Unknown",
    year: 2007,
    genre: "Drama",
    gross: 585410052,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Mission: Impossible - The Final Reckoning",
    director: "Unknown",
    year: 2025,
    genre: "Drama",
    gross: 584853227,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Monsters, Inc.",
    director: "Unknown",
    year: 2001,
    genre: "Drama",
    gross: 579771043,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Operation Red Sea",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 579330426,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Night at the Museum",
    director: "Unknown",
    year: 2006,
    genre: "Drama",
    gross: 574482479,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Godzilla x Kong: The New Empire",
    director: "Unknown",
    year: 2024,
    genre: "Drama",
    gross: 572050016,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Mission: Impossible - Dead Reckoning Part One",
    director: "Unknown",
    year: 2023,
    genre: "Drama",
    gross: 571125435,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Fifty Shades of Grey",
    director: "Unknown",
    year: 2015,
    genre: "Drama",
    gross: 569651467,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Little Mermaid",
    director: "Rob Marshall",
    year: 2023,
    genre: "Musical",
    gross: 569626289,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Kong: Skull Island",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 568652812,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "How to Train Your Dragon",
    director: "Unknown",
    year: 2025,
    genre: "Drama",
    gross: 565884995,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Smurfs",
    director: "Unknown",
    year: 2011,
    genre: "Drama",
    gross: 563892376,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Cars 2",
    director: "Unknown",
    year: 2011,
    genre: "Drama",
    gross: 559853036,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "King Kong",
    director: "Unknown",
    year: 2005,
    genre: "Drama",
    gross: 556906378,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Puss in Boots",
    director: "Unknown",
    year: 2011,
    genre: "Drama",
    gross: 554987477,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Mermaid",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 553810228,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Armageddon",
    director: "Unknown",
    year: 1998,
    genre: "Drama",
    gross: 553712773,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Day After Tomorrow",
    director: "Unknown",
    year: 2004,
    genre: "Drama",
    gross: 552639571,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Star Wars: Episode V - The Empire Strikes Back",
    director: "Unknown",
    year: 1980,
    genre: "Drama",
    gross: 550016086,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Ted",
    director: "Unknown",
    year: 2012,
    genre: "Drama",
    gross: 549368315,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Jurassic World: Rebirth",
    director: "Unknown",
    year: 2025,
    genre: "Drama",
    gross: 548762970,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Kung Fu Panda 4",
    director: "Unknown",
    year: 2024,
    genre: "Drama",
    gross: 547946428,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "American Sniper",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 547659020,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Mission: Impossible II",
    director: "Unknown",
    year: 2000,
    genre: "Drama",
    gross: 546388108,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Detective Chinatown 2",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 544185156,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Despicable Me",
    director: "Unknown",
    year: 2010,
    genre: "Drama",
    gross: 544174973,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "X-Men: Apocalypse",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 543934105,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Sherlock Holmes: A Game of Shadows",
    director: "Unknown",
    year: 2011,
    genre: "Drama",
    gross: 543848418,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Cinderella",
    director: "Unknown",
    year: 2015,
    genre: "Drama",
    gross: 542358331,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Madagascar",
    director: "Unknown",
    year: 2005,
    genre: "Drama",
    gross: 542064525,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Hotel Transylvania 3: Summer Vacation",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 541504608,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "World War Z",
    director: "Unknown",
    year: 2013,
    genre: "Drama",
    gross: 540455876,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "How to Train Your Dragon: The Hidden World",
    director: "Unknown",
    year: 2019,
    genre: "Drama",
    gross: 539987993,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Grinch",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 539294964,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Brave",
    director: "Unknown",
    year: 2012,
    genre: "Drama",
    gross: 538983207,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Simpsons Movie",
    director: "Unknown",
    year: 2007,
    genre: "Drama",
    gross: 536414293,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Dunkirk",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 533696799,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Revenant",
    director: "Unknown",
    year: 2015,
    genre: "Drama",
    gross: 532950503,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "No More Bets",
    director: "Unknown",
    year: 2023,
    genre: "Drama",
    gross: 532600264,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Meg",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 529338515,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Ralph Breaks the Internet",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 529323962,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Boss Baby",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 527965936,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "WALL·E",
    director: "Unknown",
    year: 2008,
    genre: "Drama",
    gross: 527403656,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Godzilla",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 524978362,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Sherlock Holmes",
    director: "Unknown",
    year: 2009,
    genre: "Drama",
    gross: 524028679,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Meet the Fockers",
    director: "Unknown",
    year: 2004,
    genre: "Drama",
    gross: 522657936,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Kung Fu Panda 3",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 521170825,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Ant-Man",
    director: "Unknown",
    year: 2015,
    genre: "Drama",
    gross: 519311965,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Terminator 2: Judgment Day",
    director: "Unknown",
    year: 1991,
    genre: "Drama",
    gross: 517778573,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "La La Land",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 509183536,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Venom: Let There Be Carnage",
    director: "Unknown",
    year: 2021,
    genre: "Drama",
    gross: 506813864,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Ghost",
    director: "Unknown",
    year: 1990,
    genre: "Drama",
    gross: 505703557,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Aladdin",
    director: "Guy Ritchie",
    year: 1992,
    genre: "Musical",
    gross: 504050219,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Rio 2",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 498781117,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Troy",
    director: "Unknown",
    year: 2004,
    genre: "Drama",
    gross: 497409852,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Toy Story 2",
    director: "John Lasseter",
    year: 1999,
    genre: "Animation",
    gross: 497375381,
    oscars: 0,
    rating: "G",
  },
  {
    title: "Elemental",
    director: "Unknown",
    year: 2023,
    genre: "Drama",
    gross: 496444308,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "How to Train Your Dragon",
    director: "Unknown",
    year: 2010,
    genre: "Drama",
    gross: 494879860,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Twister",
    director: "Unknown",
    year: 1996,
    genre: "Drama",
    gross: 494580615,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Oz the Great and Powerful",
    director: "Unknown",
    year: 2013,
    genre: "Drama",
    gross: 493311825,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Clash of the Titans",
    director: "Unknown",
    year: 2010,
    genre: "Drama",
    gross: 493214993,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Sonic the Hedgehog 3",
    director: "Unknown",
    year: 2024,
    genre: "Drama",
    gross: 492162604,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Maleficent: Mistress of Evil",
    director: "Unknown",
    year: 2019,
    genre: "Drama",
    gross: 491730089,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "War for the Planet of the Apes",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 490719763,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Shrek",
    director: "Unknown",
    year: 2001,
    genre: "Drama",
    gross: 488977919,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Lost in the Stars",
    director: "Unknown",
    year: 2023,
    genre: "Drama",
    gross: 487637474,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Mr. & Mrs. Smith",
    director: "Unknown",
    year: 2005,
    genre: "Drama",
    gross: 487287646,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Angels & Demons",
    director: "Unknown",
    year: 2009,
    genre: "Drama",
    gross: 485930816,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Demon Slayer: Kimetsu no Yaiba - The Movie: Mugen Train",
    director: "Unknown",
    year: 2020,
    genre: "Drama",
    gross: 485541995,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Teenage Mutant Ninja Turtles",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 485004754,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Bruce Almighty",
    director: "Unknown",
    year: 2003,
    genre: "Drama",
    gross: 484592874,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Rio",
    director: "Unknown",
    year: 2011,
    genre: "Drama",
    gross: 483866772,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Star Wars: Episode VI - Return of the Jedi",
    director: "Unknown",
    year: 1983,
    genre: "Drama",
    gross: 482466382,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Saving Private Ryan",
    director: "Unknown",
    year: 1998,
    genre: "Drama",
    gross: 482352390,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Rise of the Planet of the Apes",
    director: "Unknown",
    year: 2011,
    genre: "Drama",
    gross: 481800873,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Puss in Boots: The Last Wish",
    director: "Unknown",
    year: 2022,
    genre: "Drama",
    gross: 480466413,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Venom: The Last Dance",
    director: "Unknown",
    year: 2024,
    genre: "Drama",
    gross: 478937618,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Jaws",
    director: "Unknown",
    year: 1975,
    genre: "Drama",
    gross: 477916625,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Home Alone",
    director: "Unknown",
    year: 1990,
    genre: "Drama",
    gross: 476684675,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Ant-Man and the Wasp: Quantumania",
    director: "Unknown",
    year: 2023,
    genre: "Drama",
    gross: 476071180,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Hotel Transylvania 2",
    director: "Unknown",
    year: 2015,
    genre: "Drama",
    gross: 475186976,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Charlie and the Chocolate Factory",
    director: "Unknown",
    year: 2005,
    genre: "Drama",
    gross: 474968763,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "San Andreas",
    director: "Unknown",
    year: 2015,
    genre: "Drama",
    gross: 474609154,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Indiana Jones and the Last Crusade",
    director: "Unknown",
    year: 1989,
    genre: "Drama",
    gross: 474171806,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "It: Chapter Two",
    director: "Unknown",
    year: 2019,
    genre: "Drama",
    gross: 473123154,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Greatest Showman",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 471871490,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Wreck-It Ralph",
    director: "Unknown",
    year: 2012,
    genre: "Drama",
    gross: 471222906,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Lego Movie",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 470759687,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Godzilla vs. Kong",
    director: "Unknown",
    year: 2021,
    genre: "Drama",
    gross: 470116094,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Hangover",
    director: "Unknown",
    year: 2009,
    genre: "Drama",
    gross: 469328922,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Lucy",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 469058574,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Bumblebee",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 467989645,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Matrix",
    director: "Unknown",
    year: 1999,
    genre: "Drama",
    gross: 467841735,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Star Trek Into Darkness",
    director: "Unknown",
    year: 2013,
    genre: "Drama",
    gross: 467365246,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Gladiator",
    director: "Unknown",
    year: 2000,
    genre: "Drama",
    gross: 465516248,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Pretty Woman",
    director: "Unknown",
    year: 1990,
    genre: "Drama",
    gross: 463406268,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Gladiator II",
    director: "Unknown",
    year: 2024,
    genre: "Drama",
    gross: 462180717,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Cars",
    director: "Unknown",
    year: 2006,
    genre: "Drama",
    gross: 461996328,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Eight Hundred",
    director: "Unknown",
    year: 2020,
    genre: "Drama",
    gross: 461421559,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "X-Men: The Last Stand",
    director: "Unknown",
    year: 2006,
    genre: "Drama",
    gross: 460435291,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Moon Man",
    director: "Unknown",
    year: 2022,
    genre: "Drama",
    gross: 460237662,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "National Treasure: Book of Secrets",
    director: "Unknown",
    year: 2007,
    genre: "Drama",
    gross: 459242249,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Mission: Impossible",
    director: "Unknown",
    year: 1996,
    genre: "Drama",
    gross: 457696391,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "300",
    director: "Unknown",
    year: 2007,
    genre: "Drama",
    gross: 456082343,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Last Samurai",
    director: "Unknown",
    year: 2003,
    genre: "Drama",
    gross: 454627263,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Beetlejuice Beetlejuice",
    director: "Unknown",
    year: 2024,
    genre: "Drama",
    gross: 452000435,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Beauty and the Beast",
    director: "Bill Condon",
    year: 1991,
    genre: "Musical",
    gross: 451291298,
    oscars: 0,
    rating: "PG",
  },
  {
    title: "Dying to Survive",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 451183391,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Ocean",
    director: "Unknown",
    year: 2001,
    genre: "Drama",
    gross: 450717150,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "My People, My Country",
    director: "Unknown",
    year: 2019,
    genre: "Drama",
    gross: 450064993,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Pokémon: Detective Pikachu",
    director: "Unknown",
    year: 2019,
    genre: "Drama",
    gross: 450063166,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Thor",
    director: "Unknown",
    year: 2011,
    genre: "Drama",
    gross: 449326618,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Pearl Harbor",
    director: "Unknown",
    year: 2001,
    genre: "Drama",
    gross: 449220945,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Tarzan",
    director: "Unknown",
    year: 1999,
    genre: "Drama",
    gross: 448192603,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "John Wick: Chapter 4",
    director: "Unknown",
    year: 2023,
    genre: "Drama",
    gross: 447142521,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "1917",
    director: "Unknown",
    year: 2019,
    genre: "Drama",
    gross: 446064352,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Men in Black II",
    director: "Unknown",
    year: 2002,
    genre: "Drama",
    gross: 445135288,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Mummy Returns",
    director: "Unknown",
    year: 2001,
    genre: "Drama",
    gross: 443284916,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Alvin and the Chipmunks: The Squeakquel",
    director: "Unknown",
    year: 2009,
    genre: "Drama",
    gross: 443140005,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Bourne Ultimatum",
    director: "Unknown",
    year: 2007,
    genre: "Drama",
    gross: 442824138,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Les Misérables",
    director: "Unknown",
    year: 2012,
    genre: "Drama",
    gross: 442757529,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Transformers: Rise of the Beasts",
    director: "Unknown",
    year: 2023,
    genre: "Drama",
    gross: 441656550,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Mrs. Doubtfire",
    director: "Unknown",
    year: 1993,
    genre: "Drama",
    gross: 441286195,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Terminator Genisys",
    director: "Unknown",
    year: 2015,
    genre: "Drama",
    gross: 440603537,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Aquaman and the Lost Kingdom",
    director: "Unknown",
    year: 2023,
    genre: "Drama",
    gross: 440181226,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Warcraft",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 439048914,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "A Star Is Born",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 436433122,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Yolo",
    director: "Unknown",
    year: 2024,
    genre: "Drama",
    gross: 433600337,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Terminator 3: Rise of the Machines",
    director: "Unknown",
    year: 2003,
    genre: "Drama",
    gross: 433371112,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Shang-Chi and the Legend of the Ten Rings",
    director: "Unknown",
    year: 2021,
    genre: "Drama",
    gross: 432243292,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Die Another Day",
    director: "Unknown",
    year: 2002,
    genre: "Drama",
    gross: 431971781,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Secret Life of Pets 2",
    director: "Unknown",
    year: 2019,
    genre: "Drama",
    gross: 431164459,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Exorcist",
    director: "Unknown",
    year: 1973,
    genre: "Drama",
    gross: 430872776,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Cast Away",
    director: "Unknown",
    year: 2000,
    genre: "Drama",
    gross: 429632142,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Rampage",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 428128399,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Matrix Revolutions",
    director: "Unknown",
    year: 2003,
    genre: "Drama",
    gross: 427344325,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Intouchables",
    director: "Unknown",
    year: 2011,
    genre: "Drama",
    gross: 426590315,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Bad Boys for Life",
    director: "Unknown",
    year: 2020,
    genre: "Drama",
    gross: 426505244,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Django Unchained",
    director: "Unknown",
    year: 2012,
    genre: "Drama",
    gross: 426076293,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Dances with Wolves",
    director: "Unknown",
    year: 1990,
    genre: "Drama",
    gross: 424208848,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Pegasus 2",
    director: "Unknown",
    year: 2024,
    genre: "Drama",
    gross: 422878491,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "My People, My Homeland",
    director: "Unknown",
    year: 2020,
    genre: "Drama",
    gross: 422390820,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Successor",
    director: "Unknown",
    year: 2024,
    genre: "Drama",
    gross: 422307398,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Chronicles of Narnia: Prince Caspian",
    director: "Unknown",
    year: 2008,
    genre: "Drama",
    gross: 419665568,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Sex and the City",
    director: "Unknown",
    year: 2008,
    genre: "Drama",
    gross: 418769972,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Captain",
    director: "Unknown",
    year: 2019,
    genre: "Drama",
    gross: 417863545,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Mummy",
    director: "Unknown",
    year: 1999,
    genre: "Drama",
    gross: 417643286,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Chronicles of Narnia: The Voyage of the Dawn Treader",
    director: "Unknown",
    year: 2010,
    genre: "Drama",
    gross: 415686217,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Jason Bourne",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 415484914,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Captain America: Brave New World",
    director: "Unknown",
    year: 2025,
    genre: "Drama",
    gross: 415101577,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Wolverine",
    director: "Unknown",
    year: 2013,
    genre: "Drama",
    gross: 414828246,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Kingsman: The Secret Service",
    director: "Unknown",
    year: 2015,
    genre: "Drama",
    gross: 414351546,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The King",
    director: "Unknown",
    year: 2010,
    genre: "Drama",
    gross: 414245125,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Night at the Museum: Battle of the Smithsonian",
    director: "Unknown",
    year: 2009,
    genre: "Drama",
    gross: 413106170,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Batman",
    director: "Unknown",
    year: 1989,
    genre: "Drama",
    gross: 411569241,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Bodyguard",
    director: "Unknown",
    year: 1992,
    genre: "Drama",
    gross: 411046449,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Pacific Rim",
    director: "Unknown",
    year: 2013,
    genre: "Drama",
    gross: 411002906,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Kingsman: The Golden Circle",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 410902662,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Dune: Part One",
    director: "Unknown",
    year: 2021,
    genre: "Drama",
    gross: 410668018,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Mummy",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 409231607,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Ice Age: Collision Course",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 408754975,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Twilight",
    director: "Unknown",
    year: 2008,
    genre: "Drama",
    gross: 408522131,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Sing 2",
    director: "Unknown",
    year: 2021,
    genre: "Drama",
    gross: 408402685,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Signs",
    director: "Unknown",
    year: 2002,
    genre: "Drama",
    gross: 408247917,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "X2: X-Men United",
    director: "Unknown",
    year: 2003,
    genre: "Drama",
    gross: 407711549,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Fantastic Beasts: The Secrets of Dumbledore",
    director: "Unknown",
    year: 2022,
    genre: "Drama",
    gross: 407150844,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Uncharted",
    director: "Unknown",
    year: 2022,
    genre: "Drama",
    gross: 407141258,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Wolf of Wall Street",
    director: "Unknown",
    year: 2013,
    genre: "Drama",
    gross: 407039432,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Sonic the Hedgehog 2",
    director: "Unknown",
    year: 2022,
    genre: "Drama",
    gross: 405421518,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Your Name.",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 405340703,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Alita: Battle Angel",
    director: "Unknown",
    year: 2019,
    genre: "Drama",
    gross: 404980543,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Bad Boys: Ride or Die",
    director: "Unknown",
    year: 2024,
    genre: "Drama",
    gross: 404550184,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Mummy: Tomb of the Dragon Emperor",
    director: "Unknown",
    year: 2008,
    genre: "Drama",
    gross: 403449830,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Prometheus",
    director: "Unknown",
    year: 2012,
    genre: "Drama",
    gross: 403354469,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Gone with the Wind",
    director: "Unknown",
    year: 1939,
    genre: "Drama",
    gross: 402382193,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Eternals",
    director: "Unknown",
    year: 2021,
    genre: "Drama",
    gross: 402064899,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Tron: Legacy",
    director: "Unknown",
    year: 2010,
    genre: "Drama",
    gross: 400070675,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "F1: The Movie",
    director: "Unknown",
    year: 2025,
    genre: "Drama",
    gross: 399481913,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Mission: Impossible III",
    director: "Unknown",
    year: 2006,
    genre: "Drama",
    gross: 398479497,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Meg 2: The Trench",
    director: "Unknown",
    year: 2023,
    genre: "Drama",
    gross: 397800317,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Kingdom of the Planet of the Apes",
    director: "Unknown",
    year: 2024,
    genre: "Drama",
    gross: 397378150,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Snow White and the Huntsman",
    director: "Unknown",
    year: 2012,
    genre: "Drama",
    gross: 396592829,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Grease",
    director: "Unknown",
    year: 1978,
    genre: "Drama",
    gross: 396271103,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Mamma Mia! Here We Go Again",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 395607854,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Toy Story",
    director: "Unknown",
    year: 1995,
    genre: "Drama",
    gross: 394436586,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Spider-Man: Into the Spider-Verse",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 393602435,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Black Adam",
    director: "Unknown",
    year: 2022,
    genre: "Drama",
    gross: 393452111,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Solo: A Star Wars Story",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 392924807,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Once Upon a Time... in Hollywood",
    director: "Unknown",
    year: 2019,
    genre: "Drama",
    gross: 392105159,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Superman Returns",
    director: "Unknown",
    year: 2006,
    genre: "Drama",
    gross: 391081192,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Robin Hood: Prince of Thieves",
    director: "Unknown",
    year: 1991,
    genre: "Drama",
    gross: 390493908,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Raiders of the Lost Ark",
    director: "Unknown",
    year: 1981,
    genre: "Drama",
    gross: 389925971,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Independence Day: Resurgence",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 389681935,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Live Free or Die Hard",
    director: "Unknown",
    year: 2007,
    genre: "Drama",
    gross: 388156011,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Godzilla: King of the Monsters",
    director: "Unknown",
    year: 2019,
    genre: "Drama",
    gross: 387300138,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Monster Hunt",
    director: "Unknown",
    year: 2015,
    genre: "Drama",
    gross: 387053506,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Home",
    director: "Unknown",
    year: 2015,
    genre: "Drama",
    gross: 386041607,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Star Trek",
    director: "Unknown",
    year: 2009,
    genre: "Drama",
    gross: 385681768,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Back to the Future",
    director: "Unknown",
    year: 1985,
    genre: "Drama",
    gross: 385053307,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Happy Feet",
    director: "Unknown",
    year: 2006,
    genre: "Drama",
    gross: 384336781,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Indiana Jones and the Dial of Destiny",
    director: "Unknown",
    year: 2023,
    genre: "Drama",
    gross: 383963057,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Cars 3",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 383930656,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Ice Age",
    director: "Unknown",
    year: 2002,
    genre: "Drama",
    gross: 383257136,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Thunderbolts*",
    director: "Unknown",
    year: 2025,
    genre: "Drama",
    gross: 382073392,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Fifty Shades Darker",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 381545846,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Monsters vs. Aliens",
    director: "Unknown",
    year: 2009,
    genre: "Drama",
    gross: 381509870,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Edge of Tomorrow",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 381055527,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Mad Max: Fury Road",
    director: "Unknown",
    year: 2015,
    genre: "Drama",
    gross: 380437267,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Black Widow",
    director: "Unknown",
    year: 2021,
    genre: "Drama",
    gross: 379751655,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Godzilla",
    director: "Unknown",
    year: 1998,
    genre: "Drama",
    gross: 379014294,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "True Lies",
    director: "Unknown",
    year: 1994,
    genre: "Drama",
    gross: 378882411,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Slumdog Millionaire",
    director: "Unknown",
    year: 2008,
    genre: "Drama",
    gross: 378411362,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Taken 2",
    director: "Unknown",
    year: 2012,
    genre: "Drama",
    gross: 376152455,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "G.I. Joe: Retaliation",
    director: "Unknown",
    year: 2013,
    genre: "Drama",
    gross: 375740705,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Batman Begins",
    director: "Unknown",
    year: 2005,
    genre: "Drama",
    gross: 375406308,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Shark Tale",
    director: "Unknown",
    year: 2004,
    genre: "Drama",
    gross: 374583879,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "What Women Want",
    director: "Unknown",
    year: 2000,
    genre: "Drama",
    gross: 374111707,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Adventures of Tintin",
    director: "Unknown",
    year: 2011,
    genre: "Drama",
    gross: 373994233,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Penguins of Madagascar",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 373515621,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "X-Men Origins: Wolverine",
    director: "Unknown",
    year: 2009,
    genre: "Drama",
    gross: 373062864,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Creation of the Gods I: Kingdom of Storms",
    director: "Unknown",
    year: 2023,
    genre: "Drama",
    gross: 373021923,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Twisters",
    director: "Unknown",
    year: 2024,
    genre: "Drama",
    gross: 372262265,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Golden Compass",
    director: "Unknown",
    year: 2007,
    genre: "Drama",
    gross: 372234864,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Fifty Shades Freed",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 371985018,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Hitch",
    director: "Unknown",
    year: 2005,
    genre: "Drama",
    gross: 371594210,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Terminator Salvation",
    director: "Unknown",
    year: 2009,
    genre: "Drama",
    gross: 371353001,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Gone Girl",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 370890259,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Captain America: The First Avenger",
    director: "Unknown",
    year: 2011,
    genre: "Drama",
    gross: 370569774,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "There",
    director: "Unknown",
    year: 1998,
    genre: "Drama",
    gross: 369884651,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Fugitive",
    director: "Unknown",
    year: 1993,
    genre: "Drama",
    gross: 368875760,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Jurassic Park III",
    director: "Unknown",
    year: 2001,
    genre: "Drama",
    gross: 368780809,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "My Big Fat Greek Wedding",
    director: "Unknown",
    year: 2002,
    genre: "Drama",
    gross: 368744044,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Shazam!",
    director: "Unknown",
    year: 2019,
    genre: "Drama",
    gross: 367799011,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Hello Mr. Billionaire",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 366961907,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Die Hard with a Vengeance",
    director: "Unknown",
    year: 1995,
    genre: "Drama",
    gross: 366101666,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Nun",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 366082797,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Sinners",
    director: "Unknown",
    year: 2025,
    genre: "Drama",
    gross: 365878513,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Alvin and the Chipmunks",
    director: "Unknown",
    year: 2007,
    genre: "Drama",
    gross: 365352546,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Tenet",
    director: "Unknown",
    year: 2020,
    genre: "Drama",
    gross: 365304105,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Notting Hill",
    director: "Unknown",
    year: 1999,
    genre: "Drama",
    gross: 364015475,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "A Bug",
    director: "Unknown",
    year: 1998,
    genre: "Drama",
    gross: 363258859,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Night at the Museum: Secret of the Tomb",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 363204635,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Ocean",
    director: "Unknown",
    year: 2004,
    genre: "Drama",
    gross: 362744280,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Mary Poppins Returns",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 362529106,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Planet of the Apes",
    director: "Unknown",
    year: 2001,
    genre: "Drama",
    gross: 362211740,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Hangover Part III",
    director: "Unknown",
    year: 2013,
    genre: "Drama",
    gross: 362000072,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The World Is Not Enough",
    director: "Unknown",
    year: 1999,
    genre: "Drama",
    gross: 361832400,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Monster Hunt 2",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 361682618,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Fast & Furious",
    director: "Unknown",
    year: 2009,
    genre: "Drama",
    gross: 360405638,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Spirited Away",
    director: "Unknown",
    year: 2001,
    genre: "Drama",
    gross: 359600098,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Noah",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 359200044,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Karate Kid",
    director: "Unknown",
    year: 2010,
    genre: "Drama",
    gross: 359126022,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Home Alone 2: Lost in New York",
    director: "Unknown",
    year: 1992,
    genre: "Drama",
    gross: 358994850,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Hotel Transylvania",
    director: "Unknown",
    year: 2012,
    genre: "Drama",
    gross: 358488860,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Minority Report",
    director: "Unknown",
    year: 2002,
    genre: "Drama",
    gross: 358372926,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Top Gun",
    director: "Unknown",
    year: 1986,
    genre: "Drama",
    gross: 357288178,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Legend of Tarzan",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 357243061,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "American Beauty",
    director: "Unknown",
    year: 1999,
    genre: "Drama",
    gross: 356296601,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Apollo 13",
    director: "Unknown",
    year: 1995,
    genre: "Drama",
    gross: 355237933,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Rain Man",
    director: "Unknown",
    year: 1988,
    genre: "Drama",
    gross: 354825435,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Great Gatsby",
    director: "Unknown",
    year: 2013,
    genre: "Drama",
    gross: 353660028,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Dumbo",
    director: "Unknown",
    year: 2019,
    genre: "Drama",
    gross: 353284621,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "I, Robot",
    director: "Unknown",
    year: 2004,
    genre: "Drama",
    gross: 353133898,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Basic Instinct",
    director: "Unknown",
    year: 1992,
    genre: "Drama",
    gross: 352927224,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Murder on the Orient Express",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 352794081,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "X-Men: First Class",
    director: "Unknown",
    year: 2011,
    genre: "Drama",
    gross: 352616690,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Angry Birds Movie",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 352333929,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "GoldenEye",
    director: "Unknown",
    year: 1995,
    genre: "Drama",
    gross: 352194034,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Catch Me If You Can",
    director: "Unknown",
    year: 2002,
    genre: "Drama",
    gross: 352114312,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Now You See Me",
    director: "Unknown",
    year: 2013,
    genre: "Drama",
    gross: 351723989,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Hannibal",
    director: "Unknown",
    year: 2001,
    genre: "Drama",
    gross: 351692268,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Mask",
    director: "Unknown",
    year: 1994,
    genre: "Drama",
    gross: 351583407,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Peter Rabbit",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 351516614,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "It Ends with Us",
    director: "Unknown",
    year: 2024,
    genre: "Drama",
    gross: 351441044,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Alien: Romulus",
    director: "Unknown",
    year: 2024,
    genre: "Drama",
    gross: 350865342,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Speed",
    director: "Unknown",
    year: 1994,
    genre: "Drama",
    gross: 350448145,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Dinosaur",
    director: "Unknown",
    year: 2000,
    genre: "Drama",
    gross: 349822765,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Deep Impact",
    director: "Unknown",
    year: 1998,
    genre: "Drama",
    gross: 349464664,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Lorax",
    director: "Unknown",
    year: 2012,
    genre: "Drama",
    gross: 349305397,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Hunger Games: The Ballad of Songbirds & Snakes",
    director: "Unknown",
    year: 2023,
    genre: "Drama",
    gross: 348424489,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Maze Runner",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 348319861,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Smurfs 2",
    director: "Unknown",
    year: 2013,
    genre: "Drama",
    gross: 347545360,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "National Treasure",
    director: "Unknown",
    year: 2004,
    genre: "Drama",
    gross: 347512530,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Trolls",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 347337803,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Rush Hour 2",
    director: "Unknown",
    year: 2001,
    genre: "Drama",
    gross: 347325802,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "How the Grinch Stole Christmas",
    director: "Unknown",
    year: 2000,
    genre: "Drama",
    gross: 347162175,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "xXx: Return of Xander Cage",
    director: "Unknown",
    year: 2017,
    genre: "Drama",
    gross: 346118277,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Pocahontas",
    director: "Unknown",
    year: 1995,
    genre: "Drama",
    gross: 346079773,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Star Trek Beyond",
    director: "Unknown",
    year: 2016,
    genre: "Drama",
    gross: 343471816,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Alvin and the Chipmunks: Chipwrecked",
    director: "Unknown",
    year: 2011,
    genre: "Drama",
    gross: 342695435,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Wanted",
    director: "Unknown",
    year: 2008,
    genre: "Drama",
    gross: 342463063,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "The Flintstones",
    director: "Unknown",
    year: 1994,
    genre: "Drama",
    gross: 341631208,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "A Quiet Place",
    director: "Unknown",
    year: 2018,
    genre: "Drama",
    gross: 340955294,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Enchanted",
    director: "Unknown",
    year: 2007,
    genre: "Drama",
    gross: 340487869,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Over the Hedge",
    director: "Unknown",
    year: 2006,
    genre: "Drama",
    gross: 339795890,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "300: Rise of an Empire",
    director: "Unknown",
    year: 2014,
    genre: "Drama",
    gross: 337580051,
    oscars: 0,
    rating: "PG-13",
  },
  {
    title: "Batman Forever",
    director: "Unknown",
    year: 1995,
    genre: "Drama",
    gross: 336567158,
    oscars: 0,
    rating: "PG-13",
  },
];

// Helper function to get random movie
export const getRandomMovie = () => {
  const randomIndex = Math.floor(Math.random() * movies.length);
  return movies[randomIndex];
};

// Helper function to find movie by title
export const findMovieByTitle = (title) => {
  return movies.find(
    (movie) => movie.title.toLowerCase() === title.toLowerCase(),
  );
};

// Helper function to get movies by genre
export const getMoviesByGenre = (genre) => {
  return movies.filter(
    (movie) => movie.genre.toLowerCase() === genre.toLowerCase(),
  );
};

// Helper function to get movies by year range
export const getMoviesByYearRange = (startYear, endYear) => {
  return movies.filter(
    (movie) => movie.year >= startYear && movie.year <= endYear,
  );
};

// Helper function to get movies by director
export const getMoviesByDirector = (director) => {
  return movies.filter(
    (movie) => movie.director.toLowerCase() === director.toLowerCase(),
  );
};

// Helper function to get movies by Oscar count
export const getMoviesByOscars = (minOscars = 0) => {
  return movies.filter((movie) => movie.oscars >= minOscars);
};

// Helper function to get movies by rating
export const getMoviesByRating = (rating) => {
  return movies.filter((movie) => movie.rating === rating);
};

// Helper function to format gross revenue
export const formatGross = (gross) => {
  if (gross >= 1000000000) {
    return `$${(gross / 1000000000).toFixed(2)}B`;
  } else if (gross >= 1000000) {
    return `$${(gross / 1000000).toFixed(2)}M`;
  } else {
    return `$${gross.toLocaleString()}`;
  }
};

export default movies;
